### ISSUE TITLE
world generation issue

### ISSUE THREAD

**Issue by Tank-ACiD** [bobombolo/realterrain#10]
issue with entering a new world with mod installed

Flow:
create new world
enable realterrain mod
enter world
result: crushed under an enormous block of sand... maybe it defaults to using the default realterrain rasters and puts you at 0,0,0. It's pitch black but if you start breaking blocks you can see that you can push your way out one voxel to bedrock?

Flow:
create new world
enter world, exit world
enable realterrain mod
enter world
result: in a generated world with the ability to use realterrain mod

**Comment by bobombolo** [comment]
when you enter the game you need to use the following command:
<pre>
grant singleplayer all
</pre>

this gives you fly, fast and noclip (k, j, h keys respectively)
this could be fixed but is a common case in lua mapgen mods and in our case we will prolly want users to have these abilities by default anyway.

you wouldn't want to enter the game before you activate the mod because the area around your spawn will generate with the default mapgen and will then be part of the world.
