### ISSUE TITLE
gis file export issues

### ISSUE THREAD

**Issue by bobombolo** [bobombolo/realterrain#7]
while imlib2 reads 16bit color depth it still converts it to 8bit. this is most unfortunate. we still also do not know how negative values are handled.

**Comment by bobombolo** [comment]
might try this library next: https://luapower.com/bitmap

**Comment by Tank-ACiD** [comment]
Seems the native java image code reads in 16bit, no libs necessary. What
about

http://lua-users.org/wiki/PortableNetworkGraphicsParser

..and then is it not reading in a word (2 bytes) instead of 1 byte until
eof? Unless compressed of course.

at school today, will have time to set everything up and investigate after
lecture.

Ryan

**Comment by bobombolo** [comment]
i was trying to avoid individual libraries for different formats but it may be the way to go. the frustrating thing is that the minetest core obviously has png/bmp support built in for textures (input) and screenshots (output) but none of those methods are exposed to lua. we could look at modifying core or convincing the core developers to do so for a longer term, better performance solution.

another idea is to use the red channel for the first byte and the green channel for the second byte and the blue channel for the third byte or the presence of water.

speaking of which, we should get a set of data that contains 16 bit elevation, raster rivers and lakes cover, raster vegetation cover, raster roads, and raster POI so that I can work on the code that adds these layers to the map. I assume you have these layers all ready for your study area?

**Comment by Tank-ACiD** [comment]
looked at bitmap, seems to be in memory only table? I recall you saying
that loading an entire heightmap in memory was too much? I do see the
support for g16 and other 16bit formats which is nice but I'm not sure this
enables us to do file i/o. This lua is quite a challenge with 16bit
graphics i/o. I'm not opposed to using imagemagik, but if there is a way,
ideally, to not use a 3rd party (tho I suppose the same could be said for
libraries tho they are a little different as they are directly included in
the code) app in this process, it would make it easier for the scientific
community to embrace. If we have to tell them to do 10 steps and spend some
time with setup and configuration, they will view it as a 'hack' and not
something that is robust (is my fear).

Ryan

**Comment by bobombolo** [comment]
also imagemagick was prohibitively slow, at least calling it using lua's io interface for each pixel was, nothing even rendered. Actually I was able to get some rendering happening when I went to one DEM pixel = an entire mapchunk elevation (80x80).

you are a more careful reader than I am, i didn't even see the words 'in-memory bitmaps' that sucks.

yes having dependencies is normal. even imagemagick is just a dependency, especially in a linux system. if you can tell someone to go to their package manager and install a list of dependencies and that's all they have to do, then I think it is acceptable. windows is kindof another story...

**Comment by Tank-ACiD** [comment]
Yes, I will get that to you when I get home. I have the 16bit DEM, but it
doesn't have cover. I'll whip up a raster for the only road, I do have one
for streams when I did the watershed delineation, not lakes but I can do
that, and I can get a raster of POI (archaeological sites). Right now they
are just points, for which I should perform a manual conversion to polygon
based on estimated site size and landform (I can't just make them all
circles because some are along bluff edges), but that's later as there are
over 230.

And yes it sucks using individual libs but...for the academic community and
for the paper, I think if we show proof of concept..get 1 specific 16bit
image format working, we can expand later to be more inclusive. As it is
now, most people have access to ArcGIS which can convert most every DEM
format to 16bit. What do you think?

Ryan

**Comment by bobombolo** [comment]
actually i am going to try imagemagick via the lua wrapper rather than the command line interface.
https://github.com/leafo/magick
conveniently also a luarock
<pre>
r,g,b,a = img:get_pixel(x, y)
Get the r,g,b,a color components of a pixel in the image as doubles from 0 to 1
</pre>

there was a bug in the luarocks magick package, see https://github.com/leafo/magick/issues/13 but that will be fixed soon and is only specific to debian systems afaik

by adding another option to the settings, bit-depth, we now have working 16bit values. I am looking for ways to get the actual integer values from each pixel using the magick lib but for now I will use the imblib library for the landcover, although eventually we will only want to use one library.

with contrast-stretched images the height obviously goes really high in 16 bit.

Here is a screenshot of the a 16 bit dem with altitudes ranging around 2000m and displayed as 30m pixel size. it is far less interesting to look at and interact in this way.

![screenshot_20151020_104438](https://cloud.githubusercontent.com/assets/12679496/10616047/ff8da6f6-7717-11e5-9b91-463e50e8fcd8.png)

anyway this is the "sixteen" branch i haven't pushed it yet

**Comment by bobombolo** [comment]
16 bit now supported with the magick library, which is now the master branch. still want to test negative values with a GeoTIFF before we close this issue

**Comment by Tank-ACiD** [comment]
can't get the 16bit unsigned dem tif to render, just ends up a super flat
world.

dem.tif
range 1..551
15278x19425
1 band
lzw compression

**Comment by bobombolo** [comment]
are you able to open the file into photoshop and see anything? when I 
tried your 16bit tiff it was just all transparent.

if you can see anything in photoshop try exporting it as a 16bit PNG. 
can you export as other image formats in arcmap?

have you tried the freeware MircroDEM?

**Comment by Tank-ACiD** [comment]
will png and tif work interchangeably as acceptable formats at the moment?
I'll try PNG then.

**Comment by bobombolo** [comment]
pull the latest master
install the luarocks luafilesystem package, then you can use any file, 
yes all image types are supported, even in the branch you are using.
the latest master will help your testing go faster, being able to change 
layers from a pulldown

**Comment by Tank-ACiD** [comment]
will have to figure out how to get it compiled under Windows, going to get
and install 'cl'

**Comment by Tank-ACiD** [comment]
ok installed, got master, getting a lua error, will debug...This takes me a
while because I have to document every little thing I do in order to have
someone else re-create our steps to get the mod working (in Windows), so
please don't think I'm just slow :)

2015-10-25 01:12:35: ERROR[main]: ========== ERROR FROM LUA ===========
2015-10-25 01:12:35: ERROR[main]: Failed to load and run script from
2015-10-25 01:12:35: ERROR[main]:
I:\Minetest\bin\..\mods\realterrain\init.lua:
2015-10-25 01:12:35: ERROR[main]: C:\Program Files
(x86)\LuaRocks\2.2\lua\luaroc
ks\loader.lua:117: error loading module 'lfs' from file 'C:\Program Files
(x86)\
LuaRocks\systree\lib\lua\5.1\lfs.dll':
2015-10-25 01:12:35: ERROR[main]:       %1 is not a valid Win32 application.
2015-10-25 01:12:35: ERROR[main]: stack traceback:
2015-10-25 01:12:35: ERROR[main]:       [C]: in function 'a_loader'
2015-10-25 01:12:35: ERROR[main]:       C:\Program Files
(x86)\LuaRocks\2.2\lua\
luarocks\loader.lua:117: in function <C:\Program Files
(x86)\LuaRocks\2.2\lua\lu
arocks\loader.lua:114>
2015-10-25 01:12:35: ERROR[main]:       [C]: in function 'require'
2015-10-25 01:12:35: ERROR[main]:
I:\Minetest\bin\..\mods\realterrain\init
.lua:9: in main chunk
2015-10-25 01:12:35: ERROR[main]: ======= END OF ERROR FROM LUA ========

**Comment by bobombolo** [comment]
sorry i meant the latest master of my mod, not the minetest core...

**Comment by bobombolo** [comment]
that is the luarocks luafilesystem package missing is all

**Comment by Tank-ACiD** [comment]
oh i think I compiled it with 64bit redist, will download and install VC
redist x86 and compile under that as lua is 32bit under windows

**Comment by Tank-ACiD** [comment]
nope, was compiled as 32 bit...

C:\Program Files (x86)\LuaRocks\2.2>luarocks install luafilesystem
Installing https://luarocks.org/luafilesystem-1.6.3-1.src.rock...
Using https://luarocks.org/luafilesystem-1.6.3-1.src.rock... switching to
'build
' mode
cl /nologo /MD /O2 -c -Fosrc/lfs.obj -IC:/Program Files
(x86)/LuaRocks/2.2/inclu
de src/lfs.c
lfs.c
link -dll -def:lfs.def -out:lfs.dll C:/Program Files
(x86)/LuaRocks/2.2/lua5.1.l
ib src/lfs.obj
Microsoft (R) Incremental Linker Version 9.00.30729.01
Copyright (C) Microsoft Corporation.  All rights reserved.

   Creating library lfs.lib and object lfs.exp
mt -manifest lfs.dll.manifest -outputresource:lfs.dll;2
Microsoft (R) Manifest Tool version 5.2.3790.2076
Copyright (c) Microsoft Corporation 2005.
All rights reserved.
Updating manifest for C:\Program Files
(x86)\LuaRocks\systree/lib/luarocks/rocks

luafilesystem 1.6.3-1 is now built and installed in C:\Program Files
(x86)\LuaRo
cks\systree (license: MIT/X11)

**Comment by Tank-ACiD** [comment]
the package is compiled and it's there... I have no idea why lua doesn't
want to load it. The error, from what I have seen, is reported when people
are trying to run a 64bit dll on a 32 bit system, but I made sure to invoke
the vcvars as 32bit and it even said 32 bit compiler at package install
time. I'm at a loss on this error

**Comment by bobombolo** [comment]
i will try to remove the need for this package today by writing a pure lua function and you can test it in windows, maybe we don't need luafilesystem
